api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "wholesale-free-shipping"
type = "function"
uid = "bd77fc26-3690-10de-3f41-fbfd25db9aec9080051f"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
